battery_weight = "battery_weight"
voltage = "voltage"
max_thrust = "max_thrust"
battery_capacity = "battery_capacity"
battery_mass = "battery_mass"
discharge_rate = "discharge_rate"
propulsion = "propulsion_dialogs"
max_current = "max_current"
propeller_diameter = "propeller_diameter"


hub_position_x= "root_le_position_x"
hub_position_y= "root_le_position_y"
hub_position_z= "root_le_position_z"

rotation_x="rotation_x"
rotation_y="rotation_y"
pitch_angle= "pitch_angle"
propeller_number="propeller_number"
yz_mirror = "yz_mirror"
propeller_objects= "propeller_objects"
shroud="shroud"
shroud_number="shroud_number"
shroud_outer_diameter="shroud_outer_diameter"
shroud_inner_diameter="shroud_inner_diameter"
shroud_length="shroud_length"
shroud_taper_ratio="shroud_taper_ratio"


propeller = "propeller"
xz_mirror = "xz_mirror"
xy_mirror = "xy_mirror"
yz_mirror = "yz_mirror"

section_1_chord = "section_1_chord"
section_1_length = "section_1_length"
section_1_profile = "section_1_profile"
section_1_z = "section_1_z"
section_1_pitch_angle = "section_1_pitch_angle"

section_2_chord = "section_2_chord"
section_2_length = "section_2_length"
section_2_profile = "section_2_profile"
section_2_z = "section_2_z"
section_2_pitch_angle = "section_2_pitch_angle"

section_3_chord = "section_3_chord"
section_3_length = "section_3_length"
section_3_profile = "section_3_profile"
section_3_z = "section_3_z"
section_3_pitch_angle = "section_3_pitch_angle"

section_4_chord = "section_4_chord"
section_4_length = "section_4_length"
section_4_profile = "section_4_profile"
section_4_z = "section_4_z"
section_4_pitch_angle = "section_4_pitch_angle"

section_5_chord = "section_5_chord"
section_5_length = "section_5_length"
section_5_profile = "section_5_profile"
section_5_z = "section_5_z"
section_5_pitch_angle = "section_5_pitch_angle"
